// Ambient global type definitions for Three.js
declare module "three" {
  type AnyType = any;
  export type Group = AnyType;
  export type PointLight = AnyType;
  export type Mesh = AnyType;
  export type Scene = AnyType;
  export type PerspectiveCamera = AnyType;
  export type OrthographicCamera = AnyType;
  export type Camera = AnyType;
  export type WebGLRenderer = AnyType;
  export type Material = AnyType;
  export type MeshStandardMaterial = AnyType;
  export type MeshPhysicalMaterial = AnyType;
  export type MeshBasicMaterial = AnyType;
  export type ShaderMaterial = AnyType;
  export type PointsMaterial = AnyType;
  export type BufferGeometry = AnyType;
  export type SphereGeometry = AnyType;
  export type RingGeometry = AnyType;
  export type TorusGeometry = AnyType;
  export type TorusKnotGeometry = AnyType;
  export type BoxGeometry = AnyType;
  export type CylinderGeometry = AnyType;
  export type PlaneGeometry = AnyType;
  export type ExtrudeGeometry = AnyType;
  export type Shape = AnyType;
  export type BufferAttribute = AnyType;
  export type Points = AnyType;
  export type Clock = AnyType;
  export type TextureLoader = AnyType;
  export type CanvasTexture = AnyType;
  export type Texture = AnyType;
  export type AmbientLight = AnyType;
  export type DirectionalLight = AnyType;
  export type HemisphereLight = AnyType;
  export type Light = AnyType;
  export type Vector2 = AnyType;
  export type Vector3 = AnyType;
  export type Color = AnyType;
  export type Raycaster = AnyType;
  export type Object3D = AnyType;
  export type FogExp2 = AnyType;
  export type MathUtils = AnyType;

  export const WebGLRenderer: any;
  export const Scene: any;
  export const PerspectiveCamera: any;
  export const OrthographicCamera: any;
  export const Camera: any;
  export const Group: any;
  export const Mesh: any;
  export const MeshStandardMaterial: any;
  export const MeshPhysicalMaterial: any;
  export const MeshBasicMaterial: any;
  export const ShaderMaterial: any;
  export const PointsMaterial: any;
  export const Material: any;
  export const SphereGeometry: any;
  export const RingGeometry: any;
  export const TorusGeometry: any;
  export const TorusKnotGeometry: any;
  export const BoxGeometry: any;
  export const CylinderGeometry: any;
  export const PlaneGeometry: any;
  export const ExtrudeGeometry: any;
  export const Shape: any;
  export const BufferGeometry: any;
  export const BufferAttribute: any;
  export const Points: any;
  export const Clock: any;
  export const TextureLoader: any;
  export const CanvasTexture: any;
  export const Texture: any;
  export const PointLight: any;
  export const AmbientLight: any;
  export const DirectionalLight: any;
  export const HemisphereLight: any;
  export const Light: any;
  export const Vector2: any;
  export const Vector3: any;
  export const Color: any;
  export const Raycaster: any;
  export const Object3D: any;
  export const FogExp2: any;
  export const MathUtils: any;
  export const RepeatWrapping: any;
  export const ClampToEdgeWrapping: any;
  export const BackSide: any;
  export const DoubleSide: any;
  export const FrontSide: any;
  export const ACESFilmicToneMapping: any;
  export const AdditiveBlending: any;

  const three: any;
  export default three;
}

declare module "three/*" {
  const content: any;
  export default content;
}
